USE hr_db;

SELECT DISTINCT DEPARTMENT_ID FROM employees;

SELECT * FROM employees ORDER BY FIRST_NAME DESC;

SELECT ROUND(SUM(SALARY)) AS TOTAL_SALARIES FROM employees;

SELECT ROUND(MIN(SALARY)) AS MIN_SALARY, ROUND(MAX(SALARY)) AS MAX_SALARY FROM employees;

SELECT ROUND(AVG(SALARY)) AS AVG_SALARY FROM employees;

SELECT COUNT(EMPLOYEE_ID) AS NUMBER_OF_EMPLOYEES FROM employees;

SELECT COUNT(DISTINCT JOB_ID) AS AVAILABLE_JOBS FROM employees;

SELECT UPPER(FIRST_NAME) AS EMPLOYEE_NAMES FROM employees ORDER BY FIRST_NAME ASC;

SELECT SUBSTRING(FIRST_NAME, 1, 3) AS SHORT_NAMES FROM employees ORDER BY FIRST_NAME ASC;

SELECT CONCAT(FIRST_NAME, ' ', LAST_NAME) AS FULL_NAMES FROM employees ORDER BY FIRST_NAME ASC;

SELECT TRIM(' ' FROM FIRST_NAME) AS FIRST_NAMES FROM employees;

SELECT CONCAT(FIRST_NAME, ' ', LAST_NAME) AS FULL_NAMES,
LENGTH(CONCAT(FIRST_NAME, LAST_NAME)) AS NAME_LENGHTS
FROM employees ORDER BY FIRST_NAME ASC;

SELECT * FROM employees LIMIT 10;