USE hr_db;

SELECT CONCAT(FIRST_NAME, ' ', LAST_NAME) AS NAME, SALARY, DEPARTMENT_ID FROM employees
	WHERE DEPARTMENT_ID = 30
			AND SALARY < 10000
		OR DEPARTMENT_ID = 30 
			AND SALARY > 15000
            
		OR DEPARTMENT_ID = 100
			AND SALARY < 10000
		OR DEPARTMENT_ID = 100
			AND SALARY > 15000;

SELECT CONCAT(FIRST_NAME, ' ', LAST_NAME) AS NAME, HIRE_DATE FROM employees
	WHERE YEAR(HIRE_DATE) = 1987;

SELECT FIRST_NAME AS NAME FROM employees
	WHERE FIRST_NAME LIKE '%b%'
		AND FIRST_NAME LIKE '%c%';

SELECT employees.LAST_NAME, employees.SALARY, jobs.JOB_TITLE FROM employees
	JOIN jobs ON employees.JOB_ID = jobs.JOB_ID
		WHERE jobs.JOB_ID = 'IT_PROG'
			AND ROUND(SALARY) != 4500
			AND ROUND(SALARY) != 10000
			AND ROUND(SALARY) != 15000
            
		OR jobs.JOB_ID = 'SH_CLERK'
			AND ROUND(SALARY) != 4500
			AND ROUND(SALARY) != 10000
			AND ROUND(SALARY) != 15000;

SELECT * FROM employees
	WHERE LAST_NAME LIKE '%BLAKE%'
		OR LAST_NAME LIKE '%SCOTT%'
		OR LAST_NAME LIKE '%KING%'
		OR LAST_NAME LIKE '%FORD%';