USE hr_db;

SELECT FIRST_NAME, LAST_NAME, SALARY FROM employees
	WHERE SALARY > (SELECT SALARY FROM employees WHERE LAST_NAME = 'Bull');

SELECT FIRST_NAME, LAST_NAME FROM employees
	WHERE DEPARTMENT_ID = (SELECT DEPARTMENT_ID FROM departments WHERE DEPARTMENT_NAME = 'IT');

SELECT employees.FIRST_NAME, employees.LAST_NAME, jobs.JOB_TITLE FROM employees
	JOIN jobs ON jobs.JOB_ID = employees.JOB_ID
		WHERE jobs.JOB_TITLE LIKE '%Manager%';

SELECT FIRST_NAME, LAST_NAME, SALARY FROM employees
	WHERE SALARY > (SELECT AVG(SALARY) FROM employees);

SELECT FIRST_NAME, LAST_NAME, SALARY FROM employees
 	JOIN jobs ON jobs.JOB_ID = employees.JOB_ID
		WHERE employees.SALARY = jobs.MIN_SALARY;

SELECT FIRST_NAME, LAST_NAME, SALARY FROM employees
	WHERE SALARY = (SELECT MIN(SALARY) FROM employees);

SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, departments.DEPARTMENT_NAME FROM employees, departments
	WHERE employees.DEPARTMENT_ID = departments.DEPARTMENT_ID;

SELECT * FROM employees ORDER BY EMPLOYEE_ID DESC LIMIT 10;
