USE hr_db;

SELECT jobs.JOB_TITLE, COUNT(employees.JOB_ID) AS NUMBER_OF_EMPLOYEES FROM employees
	JOIN jobs ON jobs.JOB_ID = employees.JOB_ID
		GROUP BY employees.JOB_ID
        ORDER BY jobs.JOB_TITLE ASC;

SELECT MANAGER_ID, SALARY FROM employees
	ORDER BY SALARY ASC LIMIT 1;

SELECT employees.DEPARTMENT_ID, jobs.MAX_SALARY FROM employees
	JOIN jobs ON jobs.JOB_ID = employees.JOB_ID
		GROUP BY employees.DEPARTMENT_ID;

SELECT JOB_ID, AVG(SALARY) FROM employees
	WHERE JOB_ID != 'IT_PROG' GROUP BY JOB_ID;

SELECT JOB_ID, MAX_SALARY FROM jobs
	HAVING MAX_SALARY >= 4000;

SELECT DEPARTMENT_ID, COUNT(DEPARTMENT_ID), AVG(SALARY) FROM employees
	GROUP BY DEPARTMENT_ID
		HAVING COUNT(DEPARTMENT_ID) > 10;