USE hr_db;

SELECT EMPLOYEE_ID, REVERSE(SUBSTRING(REVERSE(EMAIL), 4)) AS SHORT_EMAIL FROM employees;

SELECT * FROM locations
	WHERE LENGTH(STREET_ADDRESS) = (SELECT MIN(LENGTH(STREET_ADDRESS)) FROM locations);

SELECT FIRST_NAME, LENGTH(FIRST_NAME) AS LENGTH_OF_FIRST_NAME FROM employees
	WHERE FIRST_NAME LIKE 'A%'
		OR FIRST_NAME LIKE 'J%'
		OR FIRST_NAME LIKE 'M%'
	ORDER BY FIRST_NAME ASC;